version: '3'

services:
  eureka:
    container_name: eureka
    build:
      context: ./eureka
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    environment:
      eureka.instance.hostname: eureka
      eureka.client.serviceUrl.defaultZone: http://eureka:8761/
  base-service:
    container_name: base-service
    build:
      context: ./base-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - "JAVA_OPTS=-DEUREKA_SERVER=http://eureka:8761/eureka -DPORT=8080"
      - server.port=8080
    links:
      - eureka
  data-service:
    container_name: data-service
    build:
      context: ./data-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - "JAVA_OPTS=-DEUREKA_SERVER=http://eureka:8761/eureka -DPORT=8081"
    links:
      - eureka